apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: ft_services
spec:
  ports:
    - name: influxdb
      port: 8086
      protocol: TCP
      nodePort: 30086
  type: LoadBalancer
  selector:
    run: influxdb
