apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-claim
  labels:
    run: influxdb
spec:
  storageClassName: influxdb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi
