apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    run: influxdb
    app: ft_services
spec:
  selector:
    matchLabels:
      run: influxdb
  template:
    metadata:
      labels:
        run: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: INFLUX_ORGANIZATION
              value: "42"
            - name: INFLUX_TOKEN
              value: "test"
            - name: INFLUX_BUCKET
              value: ft_services
          ports:
            - name: influxdb
              containerPort: 8086
          volumeMounts:
            - name: influxdb-claim
              mountPath: /root/.influxdbv2
            - name: docker-host
              mountPath: "/var/run/docker.sock"
      restartPolicy: Always
      volumes:
        - name: influxdb-claim
          persistentVolumeClaim:
            claimName: influxdb-claim
        - name: docker-host
          hostPath:
            path: /var/run/docker.sock
