apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    run: mysql
spec:
  storageClassName: mysql
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

