apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi