apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-volume
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"