apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
  labels:
    run: grafana
spec:
  storageClassName: grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi
