apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    run: grafana
    app: ft_services
spec:
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
        - name: grafana
          image: grafana
          imagePullPolicy: Never
          env:
            - name: ADMIN_PASSWORD
              value: password
          ports:
            - name: tcp
              containerPort: 3000
          volumeMounts:
            - name: grafana-claim
              mountPath: /usr/share/grafana
            - name: grafana-config-map
              mountPath: /usr/share/grafana/conf/provisioning/datasources/ft_services.yaml
              subPath: ft_services.yaml
      restartPolicy: Always
      volumes:
        - name: grafana-claim
          persistentVolumeClaim:
            claimName: grafana-claim
        - name: grafana-config-map
          configMap:
            name: grafana-config-map
