apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  labels:
    run: grafana
spec:
  storageClassName: grafana
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/gafana"
