apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      nodePort: 30001
  selector:
    run: grafana
