apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    run: nginx
    tiers: frontend
spec:
  selector:
    matchLabels:
      run: nginx
      tiers: frontend
  template:
    metadata:
      labels:
        run: nginx
        tiers: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: ssh
              containerPort: 22
            - name: wordpress
              containerPort: 5050
          volumeMounts:
            - name: wp-claim
              mountPath: /var/www/wordpress
            - name: nginx-config-map
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-map
          configMap:
            name: nginx-config-map
        - name: wp-claim
          persistentVolumeClaim:
            claimName: wp-claim
