apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    run: nginx
    app: ft_services
spec:
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: ssh
              containerPort: 22
          volumeMounts:
            - name: nginx-config-map
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-config-map
          configMap:
            name: nginx-config-map
