apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 22
      protocol: TCP
      name: ssh
      targetPort: 22
    - port: 443
      protocol: TCP
      name: https
      targetPort: 443
    - name: wordpress
      port: 80
      targetPort: 80
      protocol: TCP
    - name: pma
      port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: wordpress
