apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports:
    - name: wordpress
      port: 5050
      protocol: TCP
      targetPort: 443
  selector:
    run: wordpress