apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    run: phpmyadmin
    app: ft_services
spec:
  selector:
    matchLabels:
      run: phpmyadmin
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: pma-claim
              mountPath: /var/www/phpmyadmin
          lifecycle:
            postStart:
              exec:
                command: ["./init.sh"]
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5050
          volumeMounts:
            - name: pma-claim
              mountPath: /var/www/phpmyadmin
            - name: pma-nginx-config-map
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: pma-claim
          persistentVolumeClaim:
            claimName: pma-claim
        - name: pma-nginx-config-map
          configMap:
            name: pma-nginx-config-map
