apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pma-claim
  labels:
    run: phpmyadmin
spec:
  storageClassName: pma
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi

