apiVersion: v1
kind: ConfigMap
metadata:
  name: pma-conf
data:
  nginx.conf: |-
    <?php
    /**
    * phpMyAdmin sample configuration, you can use it as base for
    * manual configuration. For easier setup you can use setup/
    *
    * All directives are explained in documentation in the doc/ folder
    * or at <http://docs.phpmyadmin.net/>.
    *
    * @package PhpMyAdmin
    */

    /**
    * This is needed for cookie based authentication to encrypt password in
    * cookie
    */
    $cfg['blowfish_secret'] = 'qtdRoGmbc9{8IZr323xYcSN]0s)r$9b_JUnb{~Xz'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

    /**
    * Servers configuration
    */
    $i = 0;

    /**
    * First server
    */
    $i++;
    /* Authentication type */
    $cfg['Servers'][$i]['auth_type'] = 'cookie';


    /* Server parameters */
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['Servers'][$i]['port'] = 3306;
    $cfg['Servers'][$i]['connect_type'] = 'tcp';
    $cfg['Servers'][$i]['compress'] = false;
    $cfg['Servers'][$i]['AllowNoPassword'] = true;
    $cfg['Servers'][$i]['extension'] = 'mysqli';
    $cfg['AllowThirdPartyFraming'] = true;
    $cfg['TempDir'] = '/var/www/phpmyadmin/tmp';

    /**
    * Directories for saving/loading files from server
    */
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';