apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /wordpress
        backend:
          serviceName: wordpress
          servicePort: 5050
      - path: /phpmyadmin
        backend:
          serviceName: phpmyadmin
          servicePort: 5000