apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    user                            root;
    worker_processes                auto;
    error_log                       /var/log/nginx/error.log warn;
    events {
        worker_connections          1024;
    }
    http{
      include                         /etc/nginx/mime.types;
      server {
        listen 80;
        listen [::]:80;
        listen 443 ssl;
        listen [::]:443 ssl ;

        ssl_certificate /etc/ssl/certs/ft_services.crt;
        ssl_certificate_key /etc/ssl/private/ft_services.key;
        
        server_name ft_services www.ft_services ft_services.com;

        index index.html index.htm index.nginx-debian.html index.php;
        
        root /var/www;

        location ~ \.php$ {
            fastcgi_pass      127.0.0.1:9000;
            fastcgi_index     index.php;
            include           fastcgi.conf;
          }
      }
    }