apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        upstream wordpress{
          server 127.0.0.1:5050;
        }
        server {
            listen 80 default_server;
            index index.php index.html index.htm;
            error_log /var/log/nginx/error.log;
            access_log /var/log/nginx/access.log;

            location / {
              proxy_set_header        Host            $host;
              proxy_set_header        X-Real-IP       $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://wordpress;
              proxy_redirect off;
            }
        }
    }