apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    run: phpmyadmin
spec:
  selector:
    matchLabels:
      run: phpmyadmin
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          ports: 
          - name : http
            containerPort : 5000
          volumeMounts:
            - name: pma-claim
              mountPath: /var/www/phpmyadmin
          lifecycle:
            postStart:
              exec:
                command: ["./init.sh"]
      volumes:
        - name: pma-claim
          persistentVolumeClaim:
            claimName: pma-claim
