apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          env:
            - name: WP_DB_NAME
              value: wordpress
            - name: WP_DB_USERNAME
              value: root
            - name: WP_DB_HOST
              value: 127.0.0.1:3306
            - name: WP_DB_PASSWORD
              value: password
          ports:
            - containerPort: 5050
              name: http
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          env:
          - name: SSH_USER
            value: root
          - name: SSH_PASSWORD
            value: password
          ports:
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        - name: mysql
          image: mysql
          imagePullPolicy: Never
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-claim
            mountPath: /var/lib/mysql
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: mysql-claim
        persistentVolumeClaim:
          claimName: mysql-claim