apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  ports:
    - name: wordpress
      port: 5050
      protocol: TCP
      nodePort: 30050
  type: LoadBalancer
  selector:
    run: wordpress
