apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-claim
  labels:
    run: wordpress
spec:
  storageClassName: wordpress
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi

