apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    run: ftps
    app: ft_services
spec:
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 20
            - containerPort: 30100
            - containerPort: 30101
            - containerPort: 30102
            - containerPort: 30103
          volumeMounts:
            - name: wp-claim
              mountPath: /var/www/wordpress
            - name: pma-claim
              mountPath: /var/www/phpmyadmin
          env:
            - name: MINIKUBE_IP
              valueFrom:
                secretKeyRef:
                  name: minikube-ip
                  key: ip
      volumes:
        - name: wp-claim
          persistentVolumeClaim:
            claimName: wp-claim
        - name: pma-claim
          persistentVolumeClaim:
            claimName: pma-claim
